# Site settings
title: cuvivek
description: performance engineer
#baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://cuvivek.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: C U Vivek
user_description: Performance Engineer with over 9 years of experience in Banking, Telecom and Petroleum Domain. E2E Project Experience - Designing NFT Test Strategies, Execution and Analysing critical business requirements. Hands-on working experience on Microservice architecture, Kubernetes, Openshift, Kafka, Couchbase and AWS. Proficient with Profiling and Monitoring Tools like Dynatrace, JVisualVM, JConsole, Grafana and Prometheus. Experience in Performance Test Design for complex Workload Models, Execution, Monitoring, Identifying Bottlenecks and Performance tuning.
user_title: Performance Engineer
email: vivekcu81@gmail.com
twitter_username: lorem_ipsum
github_username:  cuvivek
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
